[project]
name = "note-backend"
version = "0.1.0"
requires-python = ">=3.13.5"
dependencies = [
    "asyncpg==0.31.0",
    "fastapi==0.124.0",
    "pydantic-settings==2.12.0",
    "sqlalchemy[asyncio]==2.0.44",
    "uvicorn==0.38.0",
    "uvloop==0.22.1",
]

[dependency-groups]
bot = []
