[project]
name = "note-backend"
version = "0.1.0"
requires-python = ">=3.13.5"
dependencies = [
    "fastapi==0.124.0",
    "pydantic-settings==2.12.0",
    "uvicorn==0.38.0",
    "uvloop==0.22.1",
]
